src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 */
class Produit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="integer")
     */
    private $Prix;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="produits")
     */
    private $Categorie;

    /**
     * @ORM\OneToMany(targetEntity=ImageProduit::class, mappedBy="produit", orphanRemoval=true, cascade={"persist"})
     */
    private $imageProduits;

    /**
     * @ORM\Column(type="integer")
     */
    private $stock;

    /**
     * @ORM\Column(type="boolean")
     */
    private $visible;

    /**
     * @ORM\ManyToMany(targetEntity=SousCategorie::class, inversedBy="produits")
     */
    private $SousCategorie;

    /**
     * @ORM\OneToMany(targetEntity=LigneCommande::class, mappedBy="Produit")
     */
    private $ligneCommandes;

    public function __construct()
    {
        $this->imageProduits = new ArrayCollection();
        $this->SousCategorie = new ArrayCollection();
        $this->ligneCommandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->Prix;
    }

    public function setPrix(int $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->Categorie;
    }

    public function setCategorie(?Categorie $Categorie): self
    {
        $this->Categorie = $Categorie;

        return $this;
    }

    /**
     * @return Collection|ImageProduit[]
     */
    public function getImageProduits(): Collection
    {
        return $this->imageProduits;
    }

    public function addImageProduit(ImageProduit $imageProduit): self
    {
        if (!$this->imageProduits->contains($imageProduit)) {
            $this->imageProduits[] = $imageProduit;
            $imageProduit->setProduit($this);
        }

        return $this;
    }

    public function removeImageProduit(ImageProduit $imageProduit): self
    {
        if ($this->imageProduits->removeElement($imageProduit)) {
            // set the owning side to null (unless already changed)
            if ($imageProduit->getProduit() === $this) {
                $imageProduit->setProduit(null);
            }
        }

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(bool $visible): self
    {
        $this->visible = $visible;

        return $this;
    }

    /**
     * @return Collection|SousCategorie[]
     */
    public function getSousCategorie(): Collection
    {
        return $this->SousCategorie;
    }

    public function addSousCategorie(SousCategorie $sousCategorie): self
    {
        if (!$this->SousCategorie->contains($sousCategorie)) {
            $this->SousCategorie[] = $sousCategorie;
        }

        return $this;
    }

    public function removeSousCategorie(SousCategorie $sousCategorie): self
    {
        $this->SousCategorie->removeElement($sousCategorie);

        return $this;
    }

    /**
     * @return Collection|LigneCommande[]
     */
    public function getLigneCommandes(): Collection
    {
        return $this->ligneCommandes;
    }

    public function addLigneCommande(LigneCommande $ligneCommande): self
    {
        if (!$this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes[] = $ligneCommande;
            $ligneCommande->setProduit($this);
        }

        return $this;
    }

    public function removeLigneCommande(LigneCommande $ligneCommande): self
    {
        if ($this->ligneCommandes->removeElement($ligneCommande)) {
            // set the owning side to null (unless already changed)
            if ($ligneCommande->getProduit() === $this) {
                $ligneCommande->setProduit(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getNom();
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Entity\Commande;
use App\Entity\LigneCommande;
use App\Entity\Produit;
use App\Entity\Promotions;
use App\Entity\SousCategorie;
use App\Form\LigneCommandeType;
use App\Repository\PromotionsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    /**
     * @Route("/", name="homepage")
     */
    public function index(): Response
    {
        return $this->render('default/index.html.twig', [
            'controller_name' => 'DefaultController',
        ]);
    }

    /**
     * @Route("/content/{nomCat}", name="content")
     */
    public function content(string $nomCat): Response
    {
        $categorie = $this->getDoctrine()->getRepository(Categorie::class)->findByName($nomCat)[0];
        $produits = $this->getDoctrine()->getRepository(Produit::class)->findByCategorie($categorie->getId());

        return $this->render('default/content.html.twig', [
            'categorie' => $categorie,
            'produits' => $produits
        ]);
    }

    /**
     * @Route("/content/{nomCat}/{nomSousCat}", name="content2")
     */
    public function content2(string $nomCat, string $nomSousCat): Response
    {
        $categorie = $this->getDoctrine()->getRepository(Categorie::class)->findByName($nomCat)[0];
        $sousCat = $this->getDoctrine()->getRepository(SousCategorie::class)->findByName($nomSousCat)[0];
        $produitsSousCat = $this->getDoctrine()->getRepository(Produit::class)->findByCatSousCat($categorie->getId(), $sousCat->getId());

        return $this->render('default/content2.html.twig', [
            'categorie' => $categorie,
            'sousCat' => $sousCat,
            'produitsSousCat' => $produitsSousCat
        ]);
    }

    /**
     * @Route("/item/{id}", name="item")
     */
    public function item($id, Request $request): Response
    {
        $produit = $this->getDoctrine()->getRepository(Produit::class)->find($id);

        $ligne = new LigneCommande();
            $form = $this->createForm(LigneCommandeType::class, $ligne,
            );
        $form->handleRequest($request);
        $message="";

        if ($form->isSubmitted() && $form->isValid()) {
            if(  $produit->getStock()-$ligne->getQuantite()>=0){
                $produit->setStock($produit->getStock()-$ligne->getQuantite());
                if($produit->getStock()==0){
                    //mail("supply@shoppee.fr","rupture de stock sur ".$produit->getNom(),"rupture de stock sur ".$produit->getNom());
                }
                $commande = new Commande();
                $commande->setUser($this->getUser());
                $ligne->setProduit($produit);

                $em = $this->getDoctrine()->getManager();
                $em->persist($commande);
                $em->flush();




                $ligne->setCommande($commande);
                $em->persist($ligne);
                $em->flush();
                return $this->redirectToRoute('profil');
            }else{
                $message="Vous ne pouvez pas acheter plus que la quantité";
            }





        }

        $promotions = $this->getDoctrine()->getRepository(Promotions::class)->findAll();

        foreach ($promotions as $p ) {
            if (!empty($p->getActive())) {
                $cat = $p->getCategorie()[0];
                if ($cat == $produit->getCategorie()) {
                    $taux = $p->getTaux();
                } else {
                    $taux = 0;
                }
            } else {
                $taux = 0;
            }
        }

        return $this->render('default/item.html.twig', [
            'produit' => $produit,
            'taux' => $taux,
            'form' => $form->createView(),
            'message'=> $message,
        ]);
    }

    /**
     * @Route("/profil}", name="profil")
     */
    public function profil(): Response
    {
        $username = $this->getUser()->getUsername();
        $lignes = $this->getDoctrine()->getRepository(LigneCommande::class)->findByUser($username);

        return $this->render('default/profil.html.twig', [
            'username' => $username,
            'lignes' => $lignes
        ]);
    }

    /**
     * @Route("/promotion", name="promotion")
     */
    public function promotion(): Response
    {
        $promotions = $this->getDoctrine()->getRepository(Promotions::class)->findAll();

        foreach ($promotions as $p ) {
            if (!empty($p->getActive())) {
                $cat = $p->getCategorie()[0];
                $taux = $p->getTaux();
            }
        }

        $produits = $this->getDoctrine()->getRepository(Produit::class)->findByCategorie($cat->getId());
        return $this->render('default/promotion.html.twig', [
            'produits' => $produits,
            'taux' => $taux
        ]);
    }
}

templates/default/connexion.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>

</body>
</html>

templates/default/content.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tou(te)s les {{ categorie.Nom | lower }}{% endblock %}

{% block body %}
    <main>
        <h1>{{ categorie.Nom }}</h1>
        <div class="container ">
            <div class="row row-cols-1 row-cols-md-3 g-4 ">
                {% for p in produits %}
                    {% if p.visible is not empty %}
                        <div class="col">
                            <div class="card h-100 reveal">
                                <img src="{{ asset("images/uploads/" ~ p.imageProduits[0].image) }}" class="card-img-top" alt="...">
                                <div class="card-body">
                                    <h5 class="card-title upper">{{ p.nom }}</h5>
                                    <p class="card-text">{{ p.description }}</p>
                                    <p class="card-text">{{ p.prix / 100 }}€</p>
                                    <a href="{{ path('item', {id: p.id}) }}" class="btn btn-outline-danger">Voir les détails...</a>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </main>
{% endblock %}

templates/default/content2.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tou(te)s les {{ categorie.Nom | lower}} {{ sousCat.name | lower }}{% endblock %}

{% block body %}
    <main>
        <h1>{{ categorie.Nom }} {{ sousCat.name | lower }}</h1>
        <div class="container ">
            <div class="row row-cols-1 row-cols-md-3 g-4 ">
                {% for p in produitsSousCat %}
                    {% if p.visible is not empty %}
                        <div class="col">
                            <div class="card h-100 reveal">
                                <img src="{{ asset("images/uploads/" ~ p.imageProduits[0].image) }}" class="card-img-top" alt="...">
                                <div class="card-body">
                                    <h5 class="card-title upper">{{ p.nom }}</h5>
                                    <p class="card-text">{{ p.description }}</p>
                                    <p class="card-text">{{ p.prix / 100 }}€</p>
                                    <a href="{{ path('item', {id: p.id}) }}" class="btn btn-outline-danger">Voir les détails...</a>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </main>
{% endblock %}

templates/default/dashboard.html.twig
{% extends '@!EasyAdmin/layout.html.twig' %}

{% block main %}
    <div class="content">
        <section class="content-header">
            <h4 class="title">Bienvenue dans l'administration de votre site.</h4>
        </section>
        <section class="content-panel-body with-rounded-top with-min-h-250">
            <p>
                Il y a {{ produit }} produits et {{ user }} utilisateurs dans la base de données
            </p>
            <p>Sur le menu a gauche vous pouvez modifier tout les champs de votre base de donnée, définir si un produit est actif ou activer une promotion</p>
            <p>En bref vous avez tout les outils pour administrer votre site !</p>
        </section>
    </div>
{% endblock %}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Shoppee !{% endblock %}

{% block body %}
    <main>
        <div class="home">
            <div class="text-home">
                <video width="100%" class="video" src="{{ asset('images/hebillage.mp4') }}" autoplay loop>
                </video>
                <div class="bienvenue">
                    <h1 class="white">Bienvenue chez&thinsp;<span>SHOPPEE !</span></h1>
                </div>
            </div>
        </div>
        <h1>
            Ce que nous proposons :
        </h1>
        <div class="Contenu">
            <div class="row row-cols-1 row-cols-md-3 alignement_card ">
                <div class="col">
                    <div class="card h-100">
                        <img src="{{ asset('images/chaussures.jpg') }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">Card title</h5>
                            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to
                                additional content. This content is a little bit longer.</p>
                            <a href="#" class="btn btn-danger btn-hover">En savoir plus</a>
                        </div>

                    </div>
                </div>
                <div class="col">
                    <div class="card h-100">
                        <img src="{{ asset('images/chaussures.jpg') }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">Card title</h5>
                            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to
                                additional content. This content is a little bit longer.</p>
                            <a href="#" class="btn btn-danger btn-hover">En savoir plus</a>
                        </div>

                    </div>
                </div>
                <div class="col">
                    <div class="card h-100">
                        <img src="{{ asset('images/chaussures.jpg') }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">Card title</h5>
                            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to
                                additional content. This content is a little bit longer.</p>
                            <a href="#" class="btn btn-danger btn-hover">En savoir plus</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <h1>
            Nos Promotions !
        </h1>
        <div class="Contenu">
            <div class="row row-cols-1 row-cols-md-3 alignement_card ">
                <div class="col">
                    <div class="card h-100">
                        <img src="{{ asset('images/promo_femme.png') }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">Card title</h5>
                            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to
                                additional content. This content is a little bit longer.</p>
                            <a href="#" class="btn btn-danger btn-hover">En savoir plus</a>
                        </div>

                    </div>
                </div>
                <div class="col">
                    <div class="card h-100">
                        <img src="{{ asset('images/promo_homme.png') }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">Card title</h5>
                            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to
                                additional content. This content is a little bit longer.</p>
                            <a href="#" class="btn btn-danger btn-hover">En savoir plus</a>
                        </div>

                    </div>
                </div>
                <div class="col">
                    <div class="card h-100">
                        <img src="{{ asset('images/promo_chauss.png') }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">Card title</h5>
                            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to
                                additional content. This content is a little bit longer.</p>
                            <a href="#" class="btn btn-danger btn-hover">En savoir plus</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/default/item.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ produit.nom }}{% endblock %}

{% block body %}
    <main class="mainDetails">
        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
                        aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
                        aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
                        aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{{ asset('images/uploads/' ~ produit.getImageProduits()[0]) }}" class="d-block w-100"
                         alt="...">
                </div>
                {% for i in 1..produit.getImageProduits() | length - 1 %}
                    <div class="carousel-item">
                        <img src="{{ asset('images/uploads/' ~ produit.getImageProduits()[i]) }}" class="d-block w-100"
                             alt="...">
                    </div>
                {% endfor %}
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                    data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
                    data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
        <div class="details">
            <h2>{{ produit.nom }}</h2>
            <p>{{ produit.description }}</p>
            {% if produit.stock > 10 %}
                <p style="color: green">En stock</p>
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <div>
                    <button type="submit">Acheter ce produit</button>
                </div>
                {{ form_end(form) }}
            {% elseif produit.stock == 0 %}
                <p style="color: red">Rupture de stock</p>
            {% else %}
                <p style="color: orange">Il reste {{ produit.stock }} exemplaires !</p>
                {% if message is not empty %}
                    <p>{{ message }}</p>
                {% endif %}
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <div>
                    <button type="submit">Acheter ce produit</button>
                </div>
                {{ form_end(form) }}
            {% endif %}
            <h3>Prix: {{ (produit.prix / 100) - ((taux / 100) * (produit.prix / 100)) }}€</h3>
        </div>
    </main>
{% endblock %}

templates/default/profil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon profil{% endblock %}

{% block body %}
    <main  class="mainProfil">
        {% if lignes | length == 0%}
            <h2>Vous n'avez pas encore commandé...</h2>
        {% else %}
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">N° de commande</th>
                        <th scope="col">Produit</th>
                        <th scope="col">Quantité</th>
                        <th scope="col">Prix total</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for l in lignes %}
                        <tr>
                            <th scope="row">Commande n°{{ l.id }}</th>
                            <td>{{ l.getProduit().getNom() }}</td>
                            <td>{{ l.quantite }}</td>
                            <td>{{ l.getProduit().getPrix * l.quantite / 100}}€</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
        {% endif %}
    </main>
{% endblock %}

templates/default/promotion.html.twig
{% extends 'base.html.twig' %}

{% block title %}Toutes les promotions{% endblock %}

{% block body %}
    <main>
        <h1>Promotions</h1>
        <div class="container ">
            <div class="row row-cols-1 row-cols-md-3 g-4 ">
                {% for p in produits %}
                    {% if p.visible is not empty %}
                        <div class="col">
                            <div class="card h-100 reveal">
                                <img src="{{ asset("images/uploads/" ~ p.imageProduits[0].image) }}"
                                     class="card-img-top" alt="...">
                                <div class="card-body">
                                    <h5 class="card-title upper">{{ p.nom }}</h5>
                                    <p class="card-text">{{ p.description }}</p>
                                    <p class="card-text">{{ (p.prix / 100) - ((taux / 100) * (p.prix / 100)) }}€ <span
                                                style="text-decoration: line-through; color: grey">{{ (p.prix / 100) }}€</span></p>
                                    <a href="{{ path('item', {id: p.id}) }}" class="btn btn-outline-danger">Voir les
                                        détails...</a>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </main>
{% endblock %}